[package]
name = "singularity-dotfiles-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
schemars = "1.2.1"
anyhow = "1"
os-release = "0.1.0"
tracing = "0.1.44"
tracing-subscriber = "0.3.23"
tracing-appender = "0.2.5"
cliclack = "0.5.4"
clap = { version = "4.6.1", features = ["derive"] }
which = "8"
tempfile = "3.27.0"
url = "2.5.8"
reqwest = { version = "0.13", features = ["blocking", "json"] }
semver = "1.0.28"
walkdir = "2.5.0"
dirs = "6.0.0"
chrono = "0.4.44"
rhai = { version = "1.24.0", features = ["metadata"]}
regex = "1.12.3"

[dependencies.rhai-autodocs]
version = "0.11.0"
optional = true

[[bin]]
name = "gen_docs"
required-features = ["rhai-autodocs"]
